Models/ErrorViewModel.cs
namespace futbolperuano.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Jugador.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace futbolperuano.Models
{
    public class Jugador
    {
        public string? Nombre { get; set;}
        public char? Asistencia { get; set;}
        public string? Equipo { get; set;}
        public string? Categoria  { get; set;}
        public int? Tiempo { get; set;}
        public string? Edad  { get; set;}
        public string? Genero  { get; set;}

        public double? Monto  { get; set;}
        public double? MontoTotal  { get; set;}
        public double IGV=0.19;


    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using futbolperuano.Models;

namespace futbolperuano.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/JugadorController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using futbolperuano.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;


namespace futbolperuano.Controllers
{
    [Route("[controller]")]
    public class JugadorController : Controller
    {
        private readonly ILogger<JugadorController> _logger;

        public JugadorController(ILogger<JugadorController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        
        [HttpPost]
        public IActionResult Create(Jugador objJugador)
        {
            objJugador.Monto = objJugador.Tiempo*300;
            double? igvTotal = objJugador.Monto*objJugador.IGV;
            objJugador.MontoTotal = objJugador.Monto+igvTotal;
            string? cadenaAsistencia;
            if (objJugador.Asistencia=='A')//objJugador.Asistencia=true
            {
                cadenaAsistencia = "Asistió";
            }else{//objJugador.Asistencia=false
                cadenaAsistencia = "No asistió";
            }
            
            ViewData["Message"] = string.Concat("Estimado " , objJugador.Nombre, " te estaremos contactando pronto.",
                " | El monto es: S/. ", objJugador.Monto,
                " | IGV: "+igvTotal,
                " | Asistencia: "+cadenaAsistencia,
                " | MontoTotal: S/. "+objJugador.MontoTotal);
            return View("Index");
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Jugador/Index.cshtml
@model Jugador

@{
    ViewData["Title"] = "Jugadores";
}

<h1>@ViewData["Title"]</h1>

<div class="">
    <form asp-controller="Jugador" asp-action="Create">
        <div class="row">

            <div class="col-6">
                <div class="form group">
                    <label asp-for="Equipo">Equipo:</label>
                    <select asp-for="Equipo" class="form-control">
                        <option value="Universitario">Universitario</option>
                        <option value="Alianza Lima">Alianza Lima</option>
                        <option value="Cristal">Cristal</option>
                        <option value="Cienciano">Cienciano</option>
                        <option value="Sport Boys">Sport Boys</option>
                        <option value="Atlético Grau">Atlético Grau</option>
                        <option value="Alianza Atlético">Alianza Atlético</option>
                        <option value="Garcilaso">Garcilaso</option>
                        <option value="Binacional">Binacional</option>
                    </select>
                </div>
            </div>
            <br/><br/>

            <div class="col-6">
                <div class="form group">
                    <label asp-for="Nombre">Nombre:</label>
                    <input asp-for="Nombre" class="form-control" />
                </div>
            </div>
            <br/><br/>

            <div class="col-6">
                <div class="form group">
                    <label asp-for="Categoria">Categoria:</label>
                    <select asp-for="Categoria" class="form-control">
                        <option value="Mayores">Mayores</option>
                        <option value="Sub 17">Sub 17</option>
                        <option value="Sub 20">Sub 20</option>
                    </select>
                </div>
            </div>
            <br/><br/>

            <div class="col-6">
                <div class="form group">
                    <label asp-for="Tiempo">Tiempo:</label>
                    <select asp-for="Tiempo" class="form-control">
                        <option value="6">6 Meses</option>
                        <option value="12">12 Meses</option>
                        <option value="18">18 Meses</option>
                        <option value="24">24 Meses</option>
                    </select>
                </div>
            </div>
            <br/><br/>

            <div class="col-6"  >
                <div class="form group">
                    <label asp-for="Edad">Edad:</label>
                    <input asp-for="Edad" class="form-control" />
                </div>
            </div>
            <br/><br/>
            
            <div class="col-6">
                <div class="form group">
                    <label asp-for="Genero">Género:</label>
                    <select asp-for="Genero" class="form-control">
                        <option value="M">Masculino</option>
                        <option value="F">Femenino</option>
                    </select>
                </div>
            </div>
            <br/><br/>
            
            <div class="col-6">
                <div class="form group">
                    <label class="control-label" asp-for="Asistencia"></label><br />
                    <div>
                        <label class="form-check-inline" style="display: block;">
                            <input class="form-check-input" asp-for="Asistencia" type="radio" value="A" checked>Asistió</label>
                        </label>&ensp;
                        <label class="form-check-inline" style="display: block;">
                            <input class="form-check-input" asp-for="Asistencia" type="radio" value="I">No Asistió</label>
                        </label>
                    </div>
                </div>
            </div>
            <br/><br/>
            
            <hr/>

            <div class="col-6">
                <div class="form group">
                    <button type="submit" class="btn btn-primary">Registrar</button>
                </div>
            </div>
        </div>
    </form>
    
    <h1>@ViewData["Message"]</h1>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - futbolperuano</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/futbolperuano.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">futbolperuano</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Jugador" asp-action="Index">Jugadores</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - futbolperuano - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>